import {useEffect,useState} from 'react';
import {api} from '../api';
import type {Entity} from '../demoTypes';
import type {AuditEvent,TimelineItem} from '../reviewTypes';
import EvidenceRefs from './EvidenceRefs';
const label=(s:string)=>s.replaceAll('_',' ');
const time=(s:string|null)=>s?new Date(s).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST':'Undated source claim';
const kinds=['call','transfer','report','vehicle_observation','COMMUNICATION_BURST','NEW_CONTACT_BURST','TRANSACTION_SEQUENCE','GRAPH_PATH','LEAD_GENERATED','LEAD_REVIEW_SUBMITTED','ENTITY_RESOLUTION_DECISION','RESOLUTION_DECISION_UNDONE','SOURCE_UPLOADED','SOURCE_PROCESSED','LEAD_OPENED','EVIDENCE_OPENED','INTAKE_RESET'];
export default function ActivityView({mode,nodes,onEvidence,onNetwork,initialEntity='',initialStart='',initialEnd=''}:{mode:'audit'|'timeline';nodes:Entity[];onEvidence:(id:string)=>void;onNetwork:(ids:string[])=>void;initialEntity?:string;initialStart?:string;initialEnd?:string}){
  const [events,setEvents]=useState<TimelineItem[]>([]),[audit,setAudit]=useState<AuditEvent[]>([]),[entity,setEntity]=useState(initialEntity),[kind,setKind]=useState(''),[source,setSource]=useState(''),[category,setCategory]=useState(''),[actor,setActor]=useState(''),[start,setStart]=useState(initialStart),[end,setEnd]=useState(initialEnd),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [query,setQuery]=useState(()=>{const p=new URLSearchParams();if(initialEntity)p.set('entity_id',initialEntity);if(initialStart)p.set('start',initialStart+':00+05:30');if(initialEnd)p.set('end',initialEnd+':00+05:30');return p.toString()}),[refresh,setRefresh]=useState(0);
  useEffect(()=>{let active=true;setBusy(true);setError('');const work=mode==='audit'?api.audit(query).then(r=>{if(active)setAudit(r)}):api.timeline(query).then(r=>{if(active)setEvents(r)});work.catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[mode,query,refresh]);
  function filter(nextEntity=entity){const p=new URLSearchParams();if(start)p.set('start',start+':00+05:30');if(end)p.set('end',end+':00+05:30');if(kind)p.set(mode==='audit'?'action':'event_type',kind);if(mode==='timeline'){if(nextEntity)p.set('entity_id',nextEntity);if(source)p.set('source_type',source);if(category)p.set('category',category)}else if(actor)p.set('actor',actor);setQuery(p.toString());setRefresh(r=>r+1)}
  return <section className="records-panel activity-panel"><h2>{mode==='audit'?'Audit history':'Case timeline'}</h2><p className="micro">{mode==='audit'?'Append-only application journal · no cryptographic tamper resistance. Opens identify a local demo session, not an authenticated person.':'Source assertions, extracted claims, analytical signals and actions remain distinct. Oldest first; undated claims last. Source assertions are not independently verified.'}</p>
    <div className="activity-filters"><label>From (IST)<input aria-label="Activity from" type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>To (IST)<input aria-label="Activity to" type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>{mode==='audit'?'Action':'Event type'}<select aria-label="Activity event type" value={kind} onChange={e=>setKind(e.target.value)}><option value="">All types</option>{kinds.filter(k=>mode!=='audit'||k===k.toUpperCase()).map(k=><option key={k} value={k}>{label(k)}</option>)}</select></label>
    {mode==='timeline'?<><label>Entity<select aria-label="Timeline entity" value={entity} onChange={e=>{setEntity(e.target.value);filter(e.target.value)}}><option value="">All entities</option>{nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><label>Source type<select aria-label="Timeline source type" value={source} onChange={e=>setSource(e.target.value)}><option value="">All sources</option>{['CDR','Transaction','Report','Vehicle'].map(s=><option key={s}>{s}</option>)}</select></label><label>Record category<select aria-label="Timeline category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{['OBSERVED_SOURCE_EVENT','EXTRACTED_CLAIM','ANALYTICAL_SIGNAL','HUMAN_SYSTEM_ACTION'].map(c=><option key={c}>{c}</option>)}</select></label></>:<label>Actor<input aria-label="Audit actor" value={actor} onChange={e=>setActor(e.target.value)}/></label>}<button className="primary" onClick={()=>filter()}>Apply filters</button><button onClick={()=>{setStart('');setEnd('');setKind('');setSource('');setEntity('');setCategory('');setActor('');setQuery('')}}>Clear filters</button><button onClick={()=>setRefresh(r=>r+1)}>Refresh</button></div>
    {error&&<p role="alert">{error}</p>}{busy?<p role="status">Loading activity…</p>:<div className="activity-list">{mode==='timeline'?events.map(e=><article className="activity-card" key={e.timeline_id}><span className={'activity-category '+e.category}>{label(e.category)}</span><time>{time(e.timestamp)}</time><h3>{e.title}</h3><p>{e.description}</p><div className="related-entities">{e.entity_ids.map(id=><button key={id} onClick={()=>{setEntity(id);filter(id)}}>{nodes.find(n=>n.id===id)?.label||id}</button>)}</div><div className="activity-actions"><EvidenceRefs ids={e.evidence_ids} onOpen={onEvidence}/>{e.entity_ids.length>0&&<button onClick={()=>onNetwork(e.entity_ids)}>Open in Network</button>}</div></article>):audit.map(e=><article className="activity-card" key={e.audit_event_id}><span className="activity-category HUMAN_SYSTEM_ACTION">{e.actor_type} ACTION</span><time>{time(e.created_at)}</time><h3>{label(e.action)}</h3><p>{e.actor} · {e.object_type} · {e.object_id}</p><p>{e.reason||'No reason supplied.'}</p>{Boolean(e.old_state.review_status||e.old_state.status)&&<p className="review-success">{String(e.old_state.review_status||e.old_state.status)} → {String(e.new_state.review_status||e.new_state.status)}</p>}<details><summary>Previous / new state</summary><h4>Previous</h4><pre>{JSON.stringify(e.old_state,null,2)}</pre><h4>New</h4><pre>{JSON.stringify(e.new_state,null,2)}</pre></details><EvidenceRefs ids={e.evidence_ids} onOpen={onEvidence}/></article>)}{!(mode==='audit'?audit.length:events.length)&&<p>No activity matches these filters.</p>}</div>}
  </section>;
}
