import LeadDetail from './LeadDetail';
import {ArrowLeft,ArrowRight,FileText,ShieldCheck,X,Clock3,Network} from 'lucide-react';
import EvidenceRefs from './EvidenceRefs';
import {Badge} from './WorkspaceUI';
import type {TimelineItem} from '../reviewTypes';
import type {Entity,Relationship,Lead,Source,Evidence,PathResult,Selection} from '../demoTypes';

const time=(value:string)=>new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'})+' IST';
export default function InvestigationInspector({selection,nodes,relationships,leads,lead,evidence,sources,path,loading,error,onSelect,onEvidence,onBack,onPath,onReviewed,onClose,onTimeline,onFrom,onInvestigate,events,evidenceTrail,networkRoles}:{selection:Selection;nodes:Entity[];relationships:Relationship[];leads:Lead[];lead:Lead|null;evidence:Evidence|null;sources:Source[];path:PathResult|null;loading:boolean;error:string;onSelect:(s:Selection)=>void;onEvidence:(id:string,trail?:string)=>void;onBack:()=>void;onPath:(p:PathResult)=>void;onReviewed:()=>Promise<void>;onClose:()=>void;onTimeline:(entity?:string,start?:string,end?:string)=>void;onFrom:(id:string)=>void;onInvestigate:(lead:Lead)=>void;events:TimelineItem[];evidenceTrail:string;networkRoles?:import('../demoTypes').NetworkRole[]}){
  const label=(id:string)=>nodes.find(n=>n.id===id)?.label||id;
  const refs=(ids:string[])=><EvidenceRefs ids={ids} onOpen={onEvidence}/>;
  const entity=nodes.find(n=>n.id===selection.id), relationship=relationships.find(r=>r.id===selection.id),source=sources.find(s=>s.id===selection.id);
  const role=networkRoles?.find(r=>r.entity_id===selection.id);
  const pathCoverage=path?.steps.length?Math.round(path.steps.filter(step=>step.evidence_ids.length>0).length/path.steps.length*100):0;
  const relatedLeads=leads.filter(item=>entity?item.involved_entity_ids.includes(entity.id):path?item.involved_entity_ids.some(id=>path.node_ids.includes(id)):false);
  return <aside className="drawer golden-inspector" aria-label="Investigation inspector">
    <div className="drawer-heading"><span>{selection.kind==='evidence'?'SOURCE EVIDENCE':selection.kind==='lead'?'COMPUTED LEAD / EXPLANATION':selection.kind==='path'?'PATH INTELLIGENCE':'INTELLIGENCE INSPECTOR'}</span><button aria-label="Close inspector" onClick={onClose}><X size={16}/></button></div>
    <div className="drawer-body" key={selection.kind+selection.id}>
      {selection.kind==='evidence'&&<button className="back-link" onClick={onBack}><ArrowLeft size={14}/>Back to investigation</button>}
      {loading?<div className="detail-skeleton" role="status"><p>Loading source-backed detail…</p><i/><i/><i/></div>:error?<div className="caution" role="alert">{error}</div>:selection.kind==='entity'&&entity?<>
        <div className="inspector-entity"><span className="entity-orbit"><Network size={22}/></span><div><span className="tag">Selected {entity.type}</span><h2>{entity.label}</h2><div className="record-id">{entity.identifier}</div></div></div><p className="muted">{entity.description}</p>
        {role&&<div className="role-badge" style={{margin:'10px 0',padding:'10px 12px',borderRadius:'6px',background:role.category==='BRIDGE'?'rgba(245,158,11,0.12)':role.category==='HUB'?'rgba(56,189,248,0.12)':'rgba(255,255,255,0.04)',border:'1px solid '+(role.category==='BRIDGE'?'rgba(245,158,11,0.4)':role.category==='HUB'?'rgba(56,189,248,0.4)':'rgba(255,255,255,0.1)'),borderLeft:'4px solid '+(role.category==='BRIDGE'?'#F59E0B':role.category==='HUB'?'#38BDF8':'#6B7280')}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'4px'}}><span style={{fontSize:'11px',fontWeight:800,letterSpacing:'0.05em',color:role.category==='BRIDGE'?'#F59E0B':role.category==='HUB'?'#38BDF8':'#9CA3AF'}}>NETWORK ROLE: {role.role}</span><span style={{fontSize:'10px',color:'#9CA3AF',fontFamily:'monospace'}}>Betweenness: {role.betweenness} · Degree: {role.degree}</span></div><p style={{margin:0,fontSize:'12px',color:'#E5E7EB',lineHeight:'1.4'}}>{role.reason}</p><small style={{display:'block',marginTop:'6px',fontSize:'10px',color:'#9CA3AF',fontStyle:'italic'}}>{role.disclaimer}</small></div>}
        <div className="intel-metrics"><span><small>EVIDENCE DENSITY</small><strong>{entity.evidence_ids.length} refs</strong></span><span><small>CONFIDENCE</small><strong>N/A</strong></span><span><small>EVIDENCE</small><strong>{entity.evidence_ids.length}</strong></span><span><small>SOURCES</small><strong>{sources.filter(s=>s.evidence_ids.some(id=>entity.evidence_ids.includes(id))).length}</strong></span></div>
        <div className="inspector-rule"><ShieldCheck size={14}/>Recorded association · not independently verified</div>{entity.extraction_provenance?.length?<details className="method-details"><summary>Extraction provenance · {entity.extraction_provenance.length}</summary>{entity.extraction_provenance.map((p,i)=><p className="micro" key={p.evidence_id+i}>{p.extraction_method} · {p.source_id} · {p.span_start != null ? `characters ${p.span_start}–${p.span_end}` : 'span not recorded'} · confidence {p.confidence??'not supplied'}</p>)}</details>:null}
        {entity.aliases?.length>0&&<div className="confirmed-aliases"><strong>Confirmed aliases</strong><p>{entity.aliases.join(', ')}</p><p>Original mentions: {entity.original_entity_ids.join(', ')}. Source records remain unchanged.</p></div>}<div className="entity-metrics"><span><strong>{sources.filter(s=>s.evidence_ids.some(id=>entity.evidence_ids.includes(id))).length}</strong>source collections</span><span><strong>{relationships.filter(r=>r.source===entity.id||r.target===entity.id).length}</strong>connections</span><span><strong>{entity.evidence_ids.length}</strong>evidence records</span></div><div className="inspector-actions"><button onClick={()=>onTimeline(entity.id)}><Clock3 size={14}/>Open Timeline</button><button onClick={()=>onFrom(entity.id)}><Network size={14}/>Find Connection From Here</button></div><h3>Related leads</h3>{relatedLeads.slice(0,3).map(item=><button className="source-relation" key={item.lead_id} onClick={()=>onSelect({kind:'lead',id:item.lead_id})}>{item.lead_id} · {item.review_priority}<ArrowRight size={12}/></button>)}{!relatedLeads.length&&<p className="micro">No computed lead currently centers this entity.</p>}<h3>Recent source activity</h3>{events.filter(e=>e.entity_ids.includes(entity.id)&&['OBSERVED_SOURCE_EVENT','EXTRACTED_CLAIM'].includes(e.category)).slice(-3).reverse().map(e=><button className="recent-event" key={e.timeline_id} onClick={()=>e.evidence_ids[0]?onEvidence(e.evidence_ids[0],'Entity → Event → Evidence'):onTimeline(entity.id)}><span>{e.title}<small>{e.timestamp?time(e.timestamp):'Undated claim'}</small></span><ArrowRight size={12}/></button>)}{!events.some(e=>e.entity_ids.includes(entity.id)&&['OBSERVED_SOURCE_EVENT','EXTRACTED_CLAIM'].includes(e.category))&&<p className="micro">No dated activity attached to this original mention.</p>}<h3>Source verification</h3><div className="inspector-rule"><ShieldCheck size={14}/>{entity.evidence_ids.length} source references available for human verification</div><h3>Source references</h3>{refs(entity.evidence_ids)}<h3>Connected records</h3>
        {relationships.filter(r=>r.source===entity.id||r.target===entity.id).map(r=><div className="relation" key={r.id}><button onClick={()=>onSelect({kind:'relationship',id:r.id})}>{r.type.replaceAll('_',' ')}<ArrowRight size={14}/></button><p>{label(r.source)} → {label(r.target)}</p>{refs(r.evidence_ids)}</div>)}
      </>:selection.kind==='relationship'&&relationship?<>
        <Badge tone={relationship.verification_status==='VERIFIED'?'verified':relationship.status==='inferred'?'signal':'pending'}>{relationship.verification_status}</Badge><h2>{relationship.type.replaceAll('_',' ')}</h2><p>{label(relationship.source)} → {label(relationship.target)}</p><div className="record-id">{relationship.id}</div><dl className="evidence-fields"><dt>Event count</dt><dd>{relationship.event_ids.length}</dd><dt>Source times</dt><dd>{events.filter(e=>relationship.event_ids.includes(e.object_id)||e.evidence_ids.some(id=>relationship.evidence_ids.includes(id))).filter(e=>e.timestamp).map(e=>time(e.timestamp!)).join(' · ')||'No dated event attached'}</dd><dt>Interpretation</dt><dd>{relationship.status==='inferred'?'Analytical candidate':'Source assertion'} · not independently verified</dd><dt>Confidence</dt><dd>No calibrated confidence supplied</dd></dl>{relationship.extraction_provenance?.length?<details className="method-details"><summary>Extraction provenance</summary>{relationship.extraction_provenance.map((p,i)=><p className="micro" key={p.evidence_id+i}>{p.extraction_method} · {p.source_id} · {p.span_start != null ? `characters ${p.span_start}–${p.span_end}` : 'span not recorded'} · confidence {p.confidence??'not supplied'}</p>)}</details>:null}<h3>Exact source evidence</h3>{refs(relationship.evidence_ids)}<div className="caution">The relationship reflects a source assertion. It does not establish who operated a phone or account, or imply criminal activity.</div>
      </>:selection.kind==='path'?path?<>
        <span className="tag mint">SOURCE-BACKED PATH</span><h2>{path.path_length} hops. Every link inspectable.</h2><p className="muted">{label(path.node_ids[0])} → {label(path.node_ids[path.node_ids.length-1])}</p><div className="intel-metrics path-metrics"><span><small>PATH TYPE</small><strong>Association</strong></span><span><small>CONFIDENCE</small><strong>N/A</strong></span><span><small>EVIDENCE</small><strong>{path.evidence_ids.length}</strong></span><span><small>COVERAGE</small><strong>{pathCoverage}%</strong></span></div><h3>Computed path summary</h3><p className="path-disclosure">This path exposes a reviewable association between two investigation entities across {path.path_length} source-backed hops. It is a connection to inspect, not a conclusion.</p><p className="micro">Undirected association search · maximum {path.max_depth} hops · no calibrated confidence score supplied.</p><h3>Related leads</h3>{relatedLeads.slice(0,3).map(item=><button className="source-relation" key={item.lead_id} onClick={()=>onSelect({kind:'lead',id:item.lead_id})}>{item.lead_id} · {item.review_priority}<ArrowRight size={12}/></button>)}<h3>Source verification</h3><div className="inspector-rule"><ShieldCheck size={14}/>{pathCoverage}% of path steps include source evidence</div><h3>Evidence overview</h3>{refs(path.evidence_ids)}<h3>Path steps</h3>
        <div className="path-steps">{path.steps.map((step,i)=>{const r=path.relationships.find(r=>r.id===step.relationship_id)!;return <div className="path-step" key={r.id}><span className="step">{i+1}</span><div><h4>{label(step.from_id)}</h4><button className="relationship-link" onClick={()=>onSelect({kind:'relationship',id:r.id})}>{r.type.replaceAll('_',' ')} {step.traversal==='reverse'?'(reverse traversal)':''}<ArrowRight size={12}/></button><p>{label(step.to_id)}</p>{refs(step.evidence_ids)}</div></div>})}</div><div className="caution">{path.disclaimer}</div>
      </>:<p>Choose two entities and compute a path.</p>:selection.kind==='lead'&&lead?<><div className="inspector-actions"><button onClick={()=>onInvestigate(lead)}><Network size={14}/>Investigate in Network</button><button onClick={()=>onTimeline('',lead.time_window.start.slice(0,16),lead.time_window.end.slice(0,16))}><Clock3 size={14}/>View Timeline</button></div><LeadDetail lead={lead} nodes={nodes} onEvidence={onEvidence} onSelect={onSelect} onPath={onPath} onReviewed={onReviewed}/>
      </>:selection.kind==='evidence'&&evidence?<>
        <div className="evidence-breadcrumb">{evidenceTrail} → Source record</div><Badge tone={evidence.verification_status==='VERIFIED'?'verified':'pending'}>{evidence.verification_status}</Badge><span className="tag">{evidence.source_type} · {evidence.id}</span><h2 className="source-name">{evidence.source_filename}</h2>
        <dl className="evidence-fields"><dt>Exact locator</dt><dd>{[evidence.locator.row&&`Row ${evidence.locator.row}`,evidence.locator.span_start!=null&&`Characters ${evidence.locator.span_start}–${evidence.locator.span_end} (end exclusive)`,evidence.locator.page&&`Page ${evidence.locator.page}`,evidence.locator.paragraph&&`Paragraph ${evidence.locator.paragraph}`].filter(Boolean).join(' · ')}</dd><dt>Timestamp</dt><dd>{evidence.timestamp?time(evidence.timestamp):'Not specified as an event timestamp'}</dd><dt>Fields</dt><dd>{evidence.locator.fields.join(', ')}</dd><dt>Verification</dt><dd>{evidence.verification_status}</dd></dl>
        <p className="micro">{evidence.parser_version&&`Parser: ${evidence.parser_version} · Record: ${evidence.source_record_id}`}</p><div className="eyebrow">EXACT SOURCE EXCERPT</div><blockquote className="source-excerpt">{evidence.exact_excerpt}</blockquote><h3>Related entities</h3><div className="related-entities">{evidence.entity_ids.map(id=><button key={id} onClick={()=>onSelect({kind:'entity',id})}>{label(id)}<ArrowRight size={12}/></button>)}</div><h3>Related relationships</h3>{evidence.relationship_ids.length?evidence.relationship_ids.map(id=><button key={id} className="source-relation" onClick={()=>onSelect({kind:'relationship',id})}>{id} · {relationships.find(r=>r.id===id)?.type.replaceAll('_',' ')}<ArrowRight size={12}/></button>):<p className="micro">Context evidence; no direct graph relationship asserted.</p>}<p className="micro">{evidence.source_record_id?'Extracted from an uploaded synthetic file. UNVERIFIED.':'Canonical synthetic fixture record.'}</p>
      </>:selection.kind==='source'&&source?<>
        <span className="tag">{source.type}</span><h2 className="source-name">{source.filename}</h2><p>{source.description}</p><p className="micro">Synthetic record collection · {source.evidence_ids.length} exact records</p><h3>Evidence register</h3>{source.evidence_ids.map(id=><button className="source-relation" key={id} onClick={()=>onEvidence(id)}><FileText size={14}/>{id}<ArrowRight size={14}/></button>)}
      </>:<p>Select a record to inspect its evidence.</p>}
    </div>
  </aside>;
}
