import {useState} from 'react';
import {ArrowRight,Lightbulb} from 'lucide-react';
import type {Lead,Entity} from '../demoTypes';
import {Badge,formatTime} from './WorkspaceUI';
export default function LeadQueue({leads,nodes,onOpen}:{leads:Lead[];nodes:Entity[];onOpen:(id:string)=>void}){
 const [priority,setPriority]=useState(''),[status,setStatus]=useState(''),[category,setCategory]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState('');
 const filtered=leads.filter(l=>(!priority||l.review_priority===priority)&&(!status||l.review_status===status)&&(!category||l.signal_categories.includes(category))&&(!start||Date.parse(l.generated_at)>=Date.parse(start+':00+05:30'))&&(!end||Date.parse(l.generated_at)<=Date.parse(end+':00+05:30')));
 return <section className="records-panel queue-panel"><div className="section-top"><div><h2>Lead Inbox</h2><p>Computed findings awaiting human interpretation</p></div><Lightbulb size={22}/></div><p className="priority-disclaimer">Review priority indicates examination order. It is not a probability of criminal activity.</p><div className="queue-filters"><label>Priority<select aria-label="Inbox priority" value={priority} onChange={e=>setPriority(e.target.value)}><option value="">All priorities</option>{['HIGH','MEDIUM','LOW'].map(v=><option key={v}>{v}</option>)}</select></label><label>Human review<select aria-label="Inbox review status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{[...new Set(leads.map(l=>l.review_status))].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label>Signal category<select aria-label="Inbox category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{[...new Set(leads.flatMap(l=>l.signal_categories))].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label>Generated from (IST)<input aria-label="Inbox from" type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Generated to (IST)<input aria-label="Inbox to" type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><button onClick={()=>{setPriority('');setStatus('');setCategory('');setStart('');setEnd('')}}>Clear filters</button></div><div className="queue-results">{filtered.map(l=><button className="queue-row" key={l.lead_id} aria-label={'Inspect Lead '+l.lead_id} onClick={()=>onOpen(l.lead_id)}><span className="queue-id">LEAD<br/><strong>{l.lead_id}</strong></span><span className="queue-copy"><strong>{l.title}</strong><span className="queue-badges"><Badge tone="pending">{l.review_priority} priority</Badge><Badge>{l.review_status.replaceAll('_',' ')}</Badge><Badge tone="signal">{l.signal_categories.length} signal categories</Badge></span><small>{l.signal_categories.join(' · ')} · {l.evidence_ids.length} evidence records</small><small>{l.involved_entity_ids.map(id=>nodes.find(n=>n.id===id)?.display_label||id).join(' · ')}</small><time>Generated (replay) {formatTime(l.generated_at)}</time></span><ArrowRight size={18}/></button>)}{!filtered.length&&<div className="empty"><Lightbulb size={24}/><h3>No leads match these filters</h3><p>Isolated activity does not automatically create a lead.</p></div>}</div></section>
}
