import ActivityView from './ActivityView';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Network,Files,Lightbulb,ArrowRight,ChevronRight,ChevronDown,ShieldCheck,Maximize,RotateCcw,Layers,X,FolderOpen,Clock3,PanelLeftClose,PanelLeftOpen,SlidersHorizontal,Info,UserRound,PanelRightClose,PanelRightOpen} from 'lucide-react';
import Graph,{colors} from '../Graph';
import {api} from '../api';
import type {CaseResponse,GraphData,Lead,Source,Evidence,PathResult,Selection,MatchProposal} from '../demoTypes';
import DataIntake from './DataIntake';
import ResolutionReview from './ResolutionReview';
import InvestigationInspector from './InvestigationInspector';
import '../golden.css';
import '../midnight.css';
import EntitySearch from './EntitySearch';
import CaseOverview from './CaseOverview';
import CaseHub from './CaseHub';
import LeadQueue from './LeadQueue';
import type {ProcessingSummary} from '../intakeTypes';
import type {TimelineItem,AuditEvent} from '../reviewTypes';
import CourtDossierModal from './CourtDossierModal';
import type {NetworkRole} from '../demoTypes';
type Page='network'|'sources'|'intake'|'audit'|'timeline'|'resolution'|'overview'|'leads';

export default function NetworkWorkspace(){
  const [showCases,setShowCases]=useState(true);
  const [caseData,setCase]=useState<CaseResponse|null>(null),[graph,setGraph]=useState<GraphData|null>(null);
  const [leads,setLeads]=useState<Lead[]>([]),[sources,setSources]=useState<Source[]>([]);
  const [selection,setSelection]=useState<Selection>({kind:'entity',id:'rahul'}),[previous,setPrevious]=useState<Selection>({kind:'entity',id:'rahul'});
  const [lead,setLead]=useState<Lead|null>(null),[evidence,setEvidence]=useState<Evidence|null>(null);
  const [error,setError]=useState(''),[detailError,setDetailError]=useState(''),[detailLoading,setDetailLoading]=useState(false),[retry,setRetry]=useState(0);
  const [view,setView]=useState<Page>('network'),[overview,setOverview]=useState(false),[fit,setFit]=useState(0);
  const [from,setFrom]=useState('rahul'),[to,setTo]=useState('vikram'),[depth,setDepth]=useState(8),[path,setPath]=useState<PathResult|null>(null),[pathBusy,setPathBusy]=useState(false);
  const [priorityFilter,setPriorityFilter]=useState('ALL'),[engineBusy,setEngineBusy]=useState(false);
  const [ingestedOnly,setIngestedOnly]=useState(false);
  const [verifiedOnly,setVerifiedOnly]=useState(false);
  const [focus,setFocus]=useState(''),[activityFocus,setActivityFocus]=useState<string[]>([]);
  const [collapsed,setCollapsed]=useState(false),[inspectorOpen,setInspectorOpen]=useState(true),[legend,setLegend]=useState(false),[filters,setFilters]=useState(false),[leadOpen,setLeadOpen]=useState(false);
  const [entityType,setEntityType]=useState(''),[relationType,setRelationType]=useState(''),[timeStart,setTimeStart]=useState(''),[timeEnd,setTimeEnd]=useState('');
  const [proposals,setProposals]=useState<MatchProposal[]>([]),[processing,setProcessing]=useState<ProcessingSummary|null>(null),[events,setEvents]=useState<TimelineItem[]>([]),[activity,setActivity]=useState<AuditEvent[]>([]);
  const [timelineEntity,setTimelineEntity]=useState(''),[timelineStart,setTimelineStart]=useState(''),[timelineEnd,setTimelineEnd]=useState('');
  const [resolutionId,setResolutionId]=useState('MP-rahul-rk-sharma'),[leadContext,setLeadContext]=useState<Lead|null>(null),[evidenceTrail,setEvidenceTrail]=useState('');
  const [showDossier,setShowDossier]=useState(false),[networkRoles,setNetworkRoles]=useState<NetworkRole[]>([]);
  useEffect(()=>{let active=true;Promise.all([api.proposals(),api.processing(),api.timeline()]).then(([p,s,e])=>{if(active){setProposals(p.proposals);setResolutionId(current=>p.proposals.some(item=>item.proposal_id===current)?current:(p.proposals[0]?.proposal_id||''));setProcessing(s);setEvents(e)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[retry]);
  useEffect(()=>{if(view==='overview'){let active=true;api.audit().then(a=>{if(active)setActivity(a)}).catch(e=>setError(e.message));return()=>{active=false}}},[view]);
  const pathAbort=useRef<AbortController|null>(null);
  useEffect(()=>{
    const controller=new AbortController();setError('');setCase(null);
    Promise.all([api.case(controller.signal),api.graph(controller.signal),api.leads(controller.signal),api.sources(controller.signal),api.networkRoles(controller.signal).catch(()=>({case_id:'',roles:[] as NetworkRole[]}))])
      .then(([c,g,l,s,nr])=>{setCase(c);setGraph(g);setLeads(l.leads);setSources(s.sources);setNetworkRoles(nr.roles);setFrom(c.case.source_default);setTo(c.case.target_default);setDepth(c.case.max_depth);setSelection({kind:'entity',id:c.case.source_default})})
      .catch(e=>{if(e.name!=='AbortError')setError(e.message)});
    return()=>controller.abort();
  },[retry]);
  useEffect(()=>{
    const controller=new AbortController();setDetailError('');setDetailLoading(false);
    if(selection.kind==='lead'||selection.kind==='evidence'){
      setDetailLoading(true);
      const work=selection.kind==='lead'?api.lead(selection.id,controller.signal).then(r=>setLead(r.lead)):api.evidence(selection.id,controller.signal).then(r=>setEvidence(r.evidence));
      work.catch(e=>{if(e.name!=='AbortError')setDetailError(e.message)}).finally(()=>{if(!controller.signal.aborted)setDetailLoading(false)});
    }
    return()=>controller.abort();
  },[selection.kind,selection.id]);
  useEffect(()=>()=>pathAbort.current?.abort(),[]);
  const visibleNodes=useMemo(()=>{
    if(!graph||!caseData)return [];
    const visible=new Set([...caseData.case.focus_entity_ids.filter(id=>['rahul','P101','P204','amit','A17','A31','vikram','rk-sharma','V02','A44'].includes(id)),...(path?.node_ids||[]),focus].filter(Boolean));
    if(ingestedOnly)return graph.nodes.filter(n=>n.id.startsWith('I-')&&(!entityType||n.type===entityType));
    return (overview?graph.nodes:graph.nodes.filter(n=>visible.has(n.id))).filter(n=>!entityType||n.type===entityType);
  },[graph,caseData,path,focus,overview,ingestedOnly,entityType]);
  const windowEvents=useMemo(()=>events.filter(e=>e.timestamp&&(!timeStart||Date.parse(e.timestamp)>=Date.parse(timeStart+':00+05:30'))&&(!timeEnd||Date.parse(e.timestamp)<=Date.parse(timeEnd+':00+05:30'))),[events,timeStart,timeEnd]);
  const visibleEdges=useMemo(()=>{const ids=new Set(visibleNodes.map(n=>n.id));const eventIds=new Set(windowEvents.map(e=>e.object_id)),evidenceIds=new Set(windowEvents.flatMap(e=>e.evidence_ids));return graph?.relationships.filter(r=>ids.has(r.source)&&ids.has(r.target)&&(!relationType||r.type===relationType)&&(!verifiedOnly||r.verification_status==='INVESTIGATOR_VERIFIED'||r.verification_status==='VERIFIED'||r.verification_status==='INVESTIGATOR_CORROBORATED')&&(!(timeStart||timeEnd)||!r.event_ids.length||r.event_ids.some(id=>eventIds.has(id))||r.evidence_ids.some(id=>evidenceIds.has(id))))||[]},[graph,visibleNodes,relationType,verifiedOnly,timeStart,timeEnd,windowEvents]);
  const highlighted=useMemo(()=>path?[...path.node_ids,...path.relationship_ids]:leadContext?[...leadContext.involved_entity_ids,...(graph?.relationships.filter(r=>r.evidence_ids.some(id=>leadContext.evidence_ids.includes(id))).map(r=>r.id)||[])]:activityFocus.length?[...activityFocus,...(graph?.relationships.filter(r=>activityFocus.includes(r.source)&&activityFocus.includes(r.target)).map(r=>r.id)||[])]:[],[path,leadContext,graph,activityFocus]);
  function clearFilters(){setEntityType('');setRelationType('');setTimeStart('');setTimeEnd('')}
  function navigate(page:Page){setView(page);if(page==='resolution')setSelection({kind:'resolution',id:resolutionId});else if(selection.kind==='resolution')setSelection({kind:'entity',id:from});if(page==='timeline'){setTimelineEntity('');setTimelineStart('');setTimelineEnd('')}setInspectorOpen(false)}
  function openTimeline(entity='',start='',end=''){setTimelineEntity(entity);setTimelineStart(start);setTimelineEnd(end);setView('timeline');setInspectorOpen(false)}
  function investigateLead(l:Lead){setLeadContext(l);clearFilters();setTimeStart(l.time_window.start.slice(0,16));setTimeEnd(l.time_window.end.slice(0,16));setPath(l.signals.find(s=>s.path)?.path||null);setView('network');setOverview(false);setIngestedOnly(false);setInspectorOpen(true);setSelection({kind:'lead',id:l.lead_id})}
  function select(s:Selection){setInspectorOpen(true);if(s.kind==='resolution')setResolutionId(s.id);if(s.kind==='lead'){const l=leads.find(l=>l.lead_id===s.id);if(l){setLeadContext(l);setTimeStart(l.time_window.start.slice(0,16));setTimeEnd(l.time_window.end.slice(0,16))}}if(s.kind==='entity'){const canonical=graph?.nodes.find(n=>n.original_entity_ids?.includes(s.id));if(canonical)s={kind:'entity',id:canonical.id}}setSelection(old=>old.kind===s.kind&&old.id===s.id?old:s);if(s.kind==='entity'){setFocus(s.id);if(caseData&&!caseData.case.focus_entity_ids.includes(s.id))setOverview(true)}}
  function openEvidence(id:string,trail?:string){setInspectorOpen(true);setEvidenceTrail(trail||((selection.kind==='lead'?'Lead '+selection.id:selection.kind==='path'?'Computed path':selection.kind==='resolution'?'Identity review':selection.kind==='relationship'?'Relationship '+selection.id:selection.kind==='entity'?'Entity '+selection.id:'Source record')+' → Evidence'));if(selection.kind!=='evidence')setPrevious(selection);setSelection({kind:'evidence',id})}
  function pickEntity(id:string){setIngestedOnly(id.startsWith('I-'));if(id.startsWith('I-'))setOverview(true);select({kind:'entity',id});clearFilters();setLeadContext(null);setActivityFocus([]);setView('network')}
  function clearPath(){setActivityFocus([]);pathAbort.current?.abort();setPathBusy(false);setPath(null);setLeadContext(null);clearFilters();setError('')}
  async function findPath(){
    clearFilters();setLeadContext(null);setInspectorOpen(true);
    const extracted=from.startsWith('I-')||to.startsWith('I-');setIngestedOnly(extracted);setOverview(extracted);
    pathAbort.current?.abort();const controller=new AbortController();pathAbort.current=controller;setPathBusy(true);setPath(null);setError('');
    try{const result=await api.path(from,to,depth,controller.signal);if(!controller.signal.aborted){setPath(result);setSelection({kind:'path',id:'path'});setLeadOpen(false);setFocus('')}}
    catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message)}
    finally{if(!controller.signal.aborted)setPathBusy(false)}
  }
  async function refreshResolution(){
    pathAbort.current?.abort();setPathBusy(false);
    const [g,c,s,l,p,processingData,timelineData,rolesData]=await Promise.all([api.graph(),api.case(),api.sources(),api.leads(),api.proposals(),api.processing(),api.timeline(),api.networkRoles().catch(()=>({case_id:'',roles:[] as NetworkRole[]}))]);setProposals(p.proposals);setProcessing(processingData);setEvents(timelineData);setGraph(g);setCase(c);setSources(s.sources);setLeads(l.leads);setNetworkRoles(rolesData.roles);if(selection.kind==='lead'){const current=l.leads.find(x=>x.lead_id===selection.id);setLead(current||null);if(!current)setSelection({kind:'entity',id:c.case.source_default})}
    const canonical=(id:string)=>g.nodes.find(n=>n.id===id||n.original_entity_ids?.includes(id))?.id||id;
    const start=g.nodes.some(n=>n.id===canonical(from))?canonical(from):c.case.source_default;
    const end=g.nodes.some(n=>n.id===canonical(to))?canonical(to):c.case.target_default;
    setFrom(start);setTo(end);setFocus(g.nodes.some(n=>n.id===canonical(focus))?canonical(focus):'');
    if(path){try{setPath(await api.path(start,end,depth))}catch(e){setPath(null);setError((e as Error).message)}}
  }
  async function refreshReviews(){const l=await api.leads();setLeads(l.leads);if(selection.kind==='lead')setLead(l.leads.find(x=>x.lead_id===selection.id)||null)}
  function openNetwork(){navigate('network')}
  async function rerunEngine(){setEngineBusy(true);try{await refreshResolution()}catch(e){setError((e as Error).message)}finally{setEngineBusy(false)}}
  if(!caseData||!graph)return <div className="loading"><img src="/assets/network-intel-mark.png" alt=""/><h1>Network Intel</h1><p role={error?'alert':'status'}>{error||'Opening investigation workspace…'}</p>{error&&<button onClick={()=>setRetry(retry+1)}>Retry connection</button>}</div>;
  if(showCases)return <CaseHub onOpen={()=>{setShowCases(false);setView('overview')}} onCreated={()=>{setShowCases(false);setView('intake');setInspectorOpen(false);setRetry(v=>v+1)}}/>;
  const c=caseData.case;
  const displayCaseId=c.id.replace(/^VEIL-/,'NI-');
  const pageNames:Record<Page,string>={network:'Network Investigation',overview:'Case Overview',intake:'Data Sources',sources:'Evidence Register',resolution:'Entity Resolution',leads:'Lead Inbox',timeline:'Timeline',audit:'Audit Trail'};
  const showInspector=inspectorOpen&&view!=='resolution'&&view!=='overview';
  return <div className={'app golden midnight intel-console'+(collapsed?' sidebar-collapsed':'')}>
    <header className="lab-topbar"><button className="lab-wordmark" aria-label="Open Network Intel investigation" onClick={openNetwork}><img src="/assets/network-intel-mark.png" alt=""/><strong>Network Intel</strong></button><span className="lab-product">Investigation Console</span><div className="topbar-case"><strong>{c.name}</strong><small>{displayCaseId}</small></div><EntitySearch nodes={graph.nodes} onPick={pickEntity}/><div className="synthetic"><span/>Synthetic Demonstration Data</div><span className="lab-user" title="Local demo reviewer · identity is self-declared"><UserRound size={17}/><span>Demo reviewer</span></span></header>
    <aside className="sidebar"><div className="nav-label">CASE WORKSPACE</div><nav aria-label="Investigation pages">{[{id:'overview' as Page,label:'Case Overview',icon:FolderOpen},{id:'intake' as Page,label:'Data Sources',icon:Files},{id:'resolution' as Page,label:'Entity Resolution',icon:ShieldCheck,count:proposals.filter(p=>p.status==='REVIEW'||p.status==='DEFERRED').length},{id:'network' as Page,label:'Network',icon:Network},{id:'leads' as Page,label:'Lead Inbox',icon:Lightbulb,count:leads.length},{id:'timeline' as Page,label:'Timeline',icon:Clock3},{id:'audit' as Page,label:'Audit Trail',icon:ShieldCheck}].map(item=><button key={item.id} title={item.label} aria-label={item.label} aria-current={view===item.id?'page':undefined} className={view===item.id?'active':''} onClick={()=>navigate(item.id)}><item.icon size={18}/><span className="nav-copy">{item.label}</span>{item.count!==undefined&&<span className="count">{item.count}</span>}</button>)}</nav><div className="sidebar-bottom"><ShieldCheck size={20}/><p>Leads, not accusations.<small>Evidence first.<br/>Human judgment always.</small></p><button className="collapse-nav" aria-label={collapsed?'Expand navigation':'Collapse navigation'} onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}<span className="nav-copy">Collapse sidebar</span></button></div></aside>
    <main><div className="page-title"><div><div className="eyebrow">{displayCaseId} <span>/</span> {c.status}</div><h1>{view==='overview'?pageNames[view]:c.name}</h1>{view!=='overview'&&<span className="page-context">{pageNames[view]} · Source-backed intelligence workspace</span>}</div><div className="page-actions"><button onClick={()=>setShowDossier(true)} title="Export Investigation Analysis Draft"><Files size={14}/>Analysis Draft</button>{view==='intake'&&<button onClick={()=>setView('sources')}><Files size={14}/>Evidence register</button>}{view!=='overview'&&view!=='resolution'&&<button aria-label={showInspector?'Collapse inspector':'Expand inspector'} onClick={()=>setInspectorOpen(!inspectorOpen)}>{showInspector?<PanelRightClose size={16}/>:<PanelRightOpen size={16}/>}Inspector</button>}</div></div>
    {error&&<div className="banner error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={14}/></button></div>}
    <div className={'workspace page-'+view+(showInspector?' with-inspector':'')}>
    {view==='overview'?<CaseOverview caseData={caseData} graph={graph} leads={leads} proposals={proposals} processing={processing} activity={activity} onNavigate={navigate}/>:view==='resolution'?<ResolutionReview proposalId={resolutionId} onSelect={id=>select({kind:'resolution',id})} onEvidence={openEvidence} onRefresh={refreshResolution}/>:view==='leads'?<LeadQueue leads={leads} nodes={graph.nodes} onOpen={id=>select({kind:'lead',id})}/>:view==='audit'||view==='timeline'?<ActivityView key={view+timelineEntity+timelineStart} mode={view} nodes={graph.nodes} onEvidence={openEvidence} initialEntity={timelineEntity} initialStart={timelineStart} initialEnd={timelineEnd} onNetwork={ids=>{clearPath();setActivityFocus(ids);setView('network');setOverview(true);if(ids[0])select({kind:'entity',id:ids[0]})}}/>:view==='intake'?<DataIntake onEntity={pickEntity} onEvidence={openEvidence} onRefresh={refreshResolution} onNetwork={()=>{clearPath();setIngestedOnly(true);setOverview(true);navigate('network')}} onResolution={()=>navigate('resolution')}/>:view==='network'?<section className={'network-panel'+(leadOpen?' leads-expanded':'')}>
      <div className="toolbar"><div className="network-title"><Network size={17}/><strong>Network graph</strong><span>{visibleNodes.length}/{graph.nodes.length} entities</span></div><button aria-pressed={legend} onClick={()=>setLegend(!legend)}><Info size={14}/>Legend</button><button aria-pressed={filters} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={14}/>Filters{(entityType||relationType||timeStart||timeEnd)&&' •'}</button><button className={verifiedOnly?"primary":""} aria-pressed={verifiedOnly} onClick={()=>setVerifiedOnly(!verifiedOnly)} title="Toggle verified-only relationships"><ShieldCheck size={14}/>{verifiedOnly?"Verified only":"All links"}</button><button className="view-toggle" onClick={()=>{setIngestedOnly(false);setOverview(!overview)}}><Layers size={14}/>{ingestedOnly?'Case graph':overview?'Focus path':'Graph mode'}</button><button aria-label="Fit graph" title="Fit graph" onClick={()=>setFit(fit+1)}><Maximize size={16}/>Fit</button></div>
      {filters&&<div className="network-filters"><label>Entity type<select aria-label="Graph entity type" value={entityType} onChange={e=>setEntityType(e.target.value)}><option value="">All entities</option>{Object.keys(colors).map(t=><option key={t}>{t}</option>)}</select></label><label>Relationship<select aria-label="Graph relationship type" value={relationType} onChange={e=>setRelationType(e.target.value)}><option value="">All relationships</option>{[...new Set(graph.relationships.map(r=>r.type))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label>From (IST)<input type="datetime-local" aria-label="Graph from" value={timeStart} onChange={e=>setTimeStart(e.target.value)}/></label><label>To (IST)<input type="datetime-local" aria-label="Graph to" value={timeEnd} onChange={e=>setTimeEnd(e.target.value)}/></label><button onClick={clearFilters}>Clear filters</button><p>Display filters only. Find path searches the full case graph and clears these filters.</p></div>}
      <div className="path-controls"><div className="connection-label"><span className="eyebrow">FIND CONNECTION</span><small>Build an evidence path</small></div><label><span>FROM</span><select aria-label="Path start" value={from} onChange={e=>{clearPath();setFrom(e.target.value)}}>{graph.nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><ArrowRight className="connection-arrow" size={15}/><label><span>TO</span><select aria-label="Path end" value={to} onChange={e=>{clearPath();setTo(e.target.value)}}>{graph.nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><label className="hops-field"><span>MAX HOPS</span><select aria-label="Maximum path depth" className="depth-select" value={depth} onChange={e=>{clearPath();setDepth(Number(e.target.value))}}>{[3,4,5,6,7,8].map(d=><option key={d} value={d}>{d}</option>)}</select></label><button className="primary" disabled={pathBusy} onClick={findPath}>{pathBusy?'Tracing…':'Find Path'}<ArrowRight size={15}/></button></div>
      <div className={"canvas"+(ingestedOnly?" extracted-canvas":"")}><div className="canvas-note"><span className="live-dot"/>{visibleNodes.length} of {graph.nodes.length} entities loaded · {visibleEdges.length} relationships{ingestedOnly&&" · UNVERIFIED"}<small>{ingestedOnly?'Extracted candidates · UNVERIFIED':overview?'Full network · drag to pan, scroll to zoom':'Focused investigation view'} · source assertions</small>{(timeStart||timeEnd)&&<small>Event window active · undated associations retained as context</small>}</div>
        {path&&<button className="path-pill" onClick={()=>select({kind:'path',id:'path'})}><span className="live-dot"/><strong>PATH FOUND</strong><span>{path.path_length} hops</span><span>{path.evidence_ids.length} evidence</span><ChevronRight size={13}/></button>}
        <Graph selected={selection.kind==='entity'||selection.kind==='relationship'?selection.id:''} entities={visibleNodes} edges={visibleEdges} path={highlighted} focus={focus} onSelect={(id,edge)=>select({kind:edge?'relationship':'entity',id})} fit={fit} overview={overview}/>
        <div className="canvas-bottom"><span>→ Source direction · All links have evidence{path?' · Unrelated records dimmed':''}</span>{path&&<button onClick={clearPath}><RotateCcw size={12}/>Clear path</button>}</div>
      </div>

      {path&&<section className="signal-corridor" aria-label="Signal corridor"><header><div><strong>SIGNAL CORRIDOR</strong><span>{graph.nodes.find(n=>n.id===path.node_ids[0])?.label} → {graph.nodes.find(n=>n.id===path.node_ids[path.node_ids.length-1])?.label}</span></div><div><span>{path.path_length} hops</span><span>{path.evidence_ids.length} evidence references</span><button onClick={()=>select({kind:'path',id:'path'})}>Why this matters <ChevronRight size={12}/></button></div></header><div className="corridor-track">{path.node_ids.map((id,i)=>{const node=graph.nodes.find(n=>n.id===id);return <div className="corridor-step" key={id}><button onClick={()=>select({kind:'entity',id})}><span>{i+1}</span><i className={'legend-shape '+(node?.type||'Person')}/><strong>{node?.label||id}</strong><small>{node?.type}</small></button>{i<path.node_ids.length-1&&<em>→</em>}</div>})}</div></section>}

      {legend&&<div className="legend">{Object.entries(colors).map(([type,color])=><span key={type}><i className={'legend-shape '+type} style={{background:color}}/>{type==='Account'?'Bank account':type}</span>)}<span className="edge-key">— source assertion · ⋯ analytical</span></div>}
      <div className={'lead-inbox'+(leadOpen?' expanded':'')}><div className="inbox-label"><button className="inbox-toggle" aria-expanded={leadOpen} onClick={()=>setLeadOpen(!leadOpen)}><Lightbulb size={15}/><span>LEAD INBOX</span><span className="inbox-count">{leads.length}</span><ChevronDown size={14}/></button>{leadOpen&&<><select aria-label="Review priority filter" value={priorityFilter} onChange={e=>setPriorityFilter(e.target.value)}>{['ALL','HIGH','MEDIUM','LOW'].map(p=><option key={p} value={p}>{p==='ALL'?'All priorities':p}</option>)}</select><button onClick={rerunEngine} disabled={engineBusy}>{engineBusy?'Computing…':'Re-run engine'}</button></>}</div>{leadOpen&&<div className="inbox-results">{leads.filter(l=>priorityFilter==='ALL'||l.review_priority===priorityFilter).map(l=><button key={l.lead_id} className="inbox-card" aria-label={'Open Lead '+l.lead_id} onClick={()=>select({kind:'lead',id:l.lead_id})}><span className="lead-number">{l.lead_id}</span><span className="inbox-copy"><strong>{l.title}</strong><small>{l.signal_categories.map(c=>c.replaceAll('_',' ')).join(' · ')} · {l.review_status}</small><small>Generated (replay): {new Date(l.generated_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</small></span><span className="tag amber">{l.review_priority}</span><ChevronRight size={18}/></button>)}{!leads.some(l=>priorityFilter==='ALL'||l.review_priority===priorityFilter)&&<p className="micro">No computed leads match this priority. Isolated signals do not automatically create leads.</p>}</div>}</div>
    </section>:<section className="records-panel"><div className="section-top"><div><h2>Evidence register</h2><p className="muted">{sources.length} collections · {caseData.counts.evidence} exact records. Uploaded files remain available in Data Sources.</p></div><button onClick={()=>navigate('intake')}>Data Sources</button></div><div className="source-list">{sources.map(s=><button key={s.id} className="source-card" onClick={()=>select({kind:'source',id:s.id})}><Files size={22}/><span><strong>{s.filename}</strong><small>{s.type} · {s.evidence_ids.length} records</small><p>{s.description}</p></span><ChevronRight size={16}/></button>)}</div></section>}
    {(showInspector||(view==='resolution'&&selection.kind==='evidence'))&&<InvestigationInspector onReviewed={refreshReviews} selection={selection} nodes={graph.nodes} relationships={graph.relationships} leads={leads} lead={lead} evidence={evidence} sources={sources} path={path} loading={detailLoading} error={detailError} onSelect={select} onEvidence={openEvidence} onBack={()=>setSelection(previous)} onClose={()=>{setInspectorOpen(false);if(view==='resolution')setSelection(previous)}} evidenceTrail={evidenceTrail} events={events} onTimeline={openTimeline} onFrom={id=>{setFrom(id);clearPath();setView('network')}} onInvestigate={investigateLead} onPath={p=>{clearFilters();setPath(p);setLeadOpen(false);setIngestedOnly(false);setOverview(false);setView('network');select({kind:'path',id:'path'})}} networkRoles={networkRoles}/>}
    </div>{showDossier&&<CourtDossierModal caseData={caseData} nodes={graph.nodes} relationships={graph.relationships} path={path} leads={leads} sources={sources} onClose={()=>setShowDossier(false)}/>}<footer><span>Network Intel · Synthetic investigation workspace</span><span><Clock3 size={10}/>All timestamps in IST</span><span>Evidence → Inference → Human review</span></footer>
  </main></div>;
}
