import {useEffect,useState} from 'react';
import {api} from '../api';
import type {MatchProposal,ResolutionDecision} from '../demoTypes';
import EvidenceRefs from './EvidenceRefs';
import {Badge} from './WorkspaceUI';

export default function ResolutionReview({proposalId,onSelect,onEvidence,onRefresh}:{proposalId:string;onSelect:(id:string)=>void;onEvidence:(id:string)=>void;onRefresh:()=>Promise<void>}){
  const [queue,setQueue]=useState<MatchProposal[]>([]),[proposal,setProposal]=useState<MatchProposal|null>(null),[history,setHistory]=useState<ResolutionDecision[]>([]);
  const [reviewer,setReviewer]=useState('Demo investigator'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  useEffect(()=>{const c=new AbortController();setProposal(null);setError('');setMessage('');setReason('');
    Promise.all([api.proposals(),api.proposal(proposalId,c.signal)]).then(([q,d])=>{if(!c.signal.aborted){setQueue(q.proposals);setProposal(d.proposal);setHistory(d.decisions)}}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort();
  },[proposalId]);
  async function decide(action:string){
    setBusy(true);setError('');setMessage('');
    try{
      if(action==='UNDO_CONFIRMED_MATCH')await api.undo(history[history.length-1].decision_id,reviewer,reason);
      else await api.decide(proposalId,action,reviewer,reason);
      const [q,d]=await Promise.all([api.proposals(),api.proposal(proposalId)]);setQueue(q.proposals);setProposal(d.proposal);setHistory(d.decisions);
      await onRefresh();setMessage(action==='CONFIRM_MATCH'?'Match confirmed. Canonical graph refreshed; original mentions preserved.':action==='UNDO_CONFIRMED_MATCH'?'Confirmation undone. Original entities are separate again.':'Decision recorded. Entities remain separate.');setReason('');
    }catch(e){setError((e as Error).message)}finally{setBusy(false)}
  }
  const identity=(n:MatchProposal['left_entity'],index:number)=><section className="identity-card"><span className="eyebrow">ORIGINAL MENTION {index}</span><h3>{n.display_label || n.label}</h3><p className="record-id">{n.identifier}</p><p>{n.description}</p><h4>Original source records</h4><EvidenceRefs ids={n.evidence_ids} onOpen={onEvidence}/><p className="micro">Phone and vehicle associations are compared against these records. Shared use remains possible.</p></section>;
  return <aside className="drawer golden-inspector resolution-workspace" aria-label="Entity resolution review"><div className="drawer-heading">ENTITY RESOLUTION / HUMAN REVIEW</div><div className="drawer-body">
    <label className="resolution-label">Review queue<select aria-label="Resolution proposal" disabled={busy} value={proposalId} onChange={e=>onSelect(e.target.value)}>{queue.map(p=><option key={p.proposal_id} value={p.proposal_id}>{p.right_entity.label} · {p.status}</option>)}</select></label>
    {error&&<p role="alert" className="caution">{error}</p>}{message&&<p role="status" className="resolution-success">{message}</p>}
    {proposal?<><div className="resolution-heading"><div><Badge tone={proposal.status==='CONFIRMED'?'verified':'pending'}>{proposal.status}</Badge><span className="comparison-caption">Compare source identities</span></div><div className="resolution-score"><strong>Rule score: {proposal.score.toFixed(3)}</strong><span>{proposal.recommendation} recommendation · Not a probability</span></div></div><p className="resolution-reason">{proposal.match_reason}</p><p className="priority-disclaimer">Score is not a calibrated probability. Name similarity alone is insufficient. No recommendation automatically merges records.</p>
    <div className="identity-comparison">{identity(proposal.left_entity,1)}<section className="matching-features"><h3>Supporting Evidence ({proposal.feature_comparisons.filter(f=>f.value>0).length})</h3>{proposal.feature_comparisons.filter(f=>f.value>0).map(f=><section className="resolution-feature" key={f.feature}><div className="feature-heading"><h4>{f.feature}</h4><span className="micro">{f.value.toFixed(3)} · weight {f.weight.toFixed(1)}</span></div><p>{f.explanation}</p><EvidenceRefs ids={f.evidence_ids} onOpen={onEvidence}/></section>)}{proposal.feature_comparisons.filter(f=>f.value===0).length>0&&(<><h3 style={{marginTop:'16px',color:'#94a3b8'}}>Uncorroborated / Absent Signals ({proposal.feature_comparisons.filter(f=>f.value===0).length})</h3>{proposal.feature_comparisons.filter(f=>f.value===0).map(f=><section className="resolution-feature" style={{opacity:0.75}} key={f.feature}><div className="feature-heading"><h4>{f.feature}</h4><span className="micro">{f.value.toFixed(3)} · weight {f.weight.toFixed(1)}</span></div><p>{f.explanation}</p><EvidenceRefs ids={f.evidence_ids} onOpen={onEvidence}/></section>)}</>)}</section>{identity(proposal.right_entity,2)}</div>
    <section className="resolution-decision decision-bar"><label className="resolution-label">Reviewer<input aria-label="Reviewer" value={reviewer} onChange={e=>setReviewer(e.target.value)} maxLength={100} disabled={busy}/></label><label className="resolution-label">Decision reason<textarea aria-label="Decision reason" value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} disabled={busy} placeholder="Cite the phone and vehicle evidence reviewed…"/></label><div><span className="eyebrow">HUMAN DECISION</span><div className="resolution-actions">{(proposal.status==='CONFIRMED'?['UNDO_CONFIRMED_MATCH']:['CONFIRM_MATCH','REJECT_MATCH','DEFER']).map(action=><button key={action} disabled={busy||!reviewer.trim()||!reason.trim()} className={action==='CONFIRM_MATCH'?'primary':''} onClick={()=>decide(action)}>{busy?'Saving…':action==='CONFIRM_MATCH'?'Confirm Match':action==='REJECT_MATCH'?'Reject Match':action==='DEFER'?'Defer':'Undo'}</button>)}</div><small>Canonical projection only. Original evidence is preserved.</small></div></section>
    <details className="resolution-method"><summary>Scoring policy, limitations and decision history · {history.length}</summary><p className="micro">No separate conflict feature is supplied. Missing data is not proof of agreement.</p><p className="micro">{proposal.algorithm_version} · fixed weights, not statistically calibrated. A strong YES suggestion requires at least two exact shared identifiers; REVIEW accepts one strong identifier or compatible name. Shared assets can have multiple users. Undo is available after confirmation.</p>{history.slice().reverse().map(d=><div className="resolution-feature" key={d.decision_id}><strong>{d.action.replaceAll('_',' ')}</strong><p>{d.reason}</p><p className="micro">{d.reviewer} · {new Date(d.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST · {d.decision_id}</p></div>)}</details>
    </>:!error&&<p role="status">Loading resolution evidence…</p>}
  </div></aside>;
}
