import fs from 'node:fs/promises';
import {Presentation, PresentationFile} from '@oai/artifact-tool';
import {resolvePresentationFont, applyPresentationChartFont, finalizePresentation} from 'file:///C:/Users/tanis/.codex/plugins/cache/openai-primary-runtime/presentations/26.904.11930/skills/presentations/container_tools/artifact_tool_utils.mjs';
const ROOT='Z:/XLab/New/Network Intel';
const W=ROOT+'/artifacts/hackathon-pack';
const SK='C:/Users/tanis/.codex/plugins/cache/openai-primary-runtime/presentations/26.904.11930/skills/presentations';
const family=resolvePresentationFont();
console.log('Font:',family);
const p=Presentation.create({slideSize:{width:1280,height:720}});
const c={bg:'#09121D',ink:'#F3F7FA',muted:'#B2C2D0',cyan:'#66E0EA',amber:'#F2CC88'};
function txt(s,t,x,y,w,h,size=28,color=c.ink,bold=false){let b=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});b.text=t;b.text.style={typeface:family,fontSize:size,color,bold,autoFit:'none'};return b;}
function base(title,num,note,source=''){let s=p.slides.add();s.background.fill=c.bg;txt(s,title,64,47,1152,104,44,c.ink,true);txt(s,String(num).padStart(2,'0'),1160,669,55,26,16,c.muted);s.speakerNotes.textFrame.setText(note+'\n\nSources / verification:\n'+source);return s;}
async function shot(s,name,x,y,w,h){s.images.add({blob:new Uint8Array(await fs.readFile(ROOT+'/artifacts/first-round/screenshots/'+name)),contentType:'image/png',alt:'Pehle captured synthetic prototype run, VEIL naam ke saath',fit:'contain',position:{left:x,top:y,width:w,height:h}});}
const notes=[];
function note(n,t){notes.push({slide:n,text:t});return t;}
let s=base('Network Intel',1,note(1,'Namaste judges. Ek report mein R.K. Sharma likha hai, call record mein ek phone number hai, aur transaction file mein ek account. Investigator ko samajhna hai ki yeh records kaise connected hain. Network Intel in records ko source-linked graph mein jodta hai, taaki har lead ka evidence inspect ho sake. Aaj hum synthetic Operation Trinetra dikhayenge. Final conclusion investigator ka rahega.'),'Repository README.md; current frontend; live production deployment verified in this task history.');
txt(s,'Records ke beech connection.\nHar lead ke saath evidence.',64,215,880,190,55,c.cyan,true);
txt(s,'Internal hackathon prototype pitch',64,455,900,45,27,c.muted);
txt(s,'Synthetic Operation Trinetra',64,515,900,45,24,c.muted);
s.images.add({blob:new Uint8Array(await fs.readFile(ROOT+'/frontend/public/assets/network-intel-mark.png')),contentType:'image/png',alt:'Network Intel logo',fit:'contain',position:{left:1000,top:235,width:150,height:150}});
txt(s,'veil-network-intel.vercel.app',64,617,1000,35,23,c.ink);
s=base('Problem: records alag, investigation connected',2,note(2,'Hum jis pain point par focus kar rahe hain woh fragmented records hain. Report, CDR aur transactions alag hone se identity aur relationship ko manually cross-check karna padta hai. Hamara user authorized investigator ya analyst hai. Existing brief SIH26189 se map hota hai, lekin official PS wording aur college format abhi SPOC se confirm karna hai. Hum agency data integration ka claim nahi kar rahe.'),'README-PREVIOUS.md; SIH-SCOPE-FREEZE.md. PS working reference only: https://sihone.pages.dev/ps/26189 (third-party mirror, official text unverified).');
txt(s,'01  Alag source files',64,190,530,45,31,c.cyan,true);txt(s,'Reports, CDR aur transactions ko\nmanual cross-check karna padta hai.',64,250,530,105,28,c.muted);
txt(s,'02  Uncertain identity',680,190,530,45,31,c.cyan,true);txt(s,'Similar naam ko same person maan lene\nse galat connection ban sakta hai.',680,250,530,105,28,c.muted);
txt(s,'03  Lead ka reason',64,420,530,45,31,c.cyan,true);txt(s,'Analyst ko source aur timing ke saath\nreview karne layak context chahiye.',64,480,530,100,28,c.muted);
txt(s,'Target user',680,420,530,45,31,c.cyan,true);txt(s,'Authorized investigator / analyst\nCurrent scope: synthetic case',680,480,530,100,28,c.muted);
txt(s,'Working PS: SIH26189. Official wording aur submission format ki confirmation pending.',64,638,1080,32,18,c.amber);
s=base('Solution: source se reviewed lead tak',3,note(3,'Yeh hamare prototype ka pehle captured run hai, jab product ka naam VEIL tha. Ab naam Network Intel hai. Screen par path backend compute karta hai. Investigator har edge ka evidence khol sakta hai. Identity review reversible hai aur lead review audit trail mein record hota hai. Is integrated workflow ko hum apna contribution keh rahe hain, world-first algorithm nahi.'),'artifacts/first-round/screenshots/03-network-path.png; backend/demo_paths.py; backend/resolution.py; backend/review_store.py.');
await shot(s,'03-network-path.png',64,175,810,455);txt(s,'Identity review',920,198,300,44,28,c.cyan,true);txt(s,'Candidate ko evidence\nke saath confirm karo.',920,250,300,95,25,c.muted);txt(s,'Source-linked path',920,376,300,44,28,c.cyan,true);txt(s,'Har relationship ka\noriginal record kholo.',920,427,300,95,25,c.muted);txt(s,'Pehle captured synthetic run. Screenshot mein purana product naam VEIL hai.',64,643,1080,29,18,c.muted);
s=base('Lead 17 ka explainable signal',4,note(4,'Synthetic case mein pichhle saat complete din ka median do outgoing calls per day hai. Event day par replay time tak gyarah calls hain. Configured threshold max of five calls aur three times baseline hai, yani six. Isliye communication signal trigger hota hai. Teen connected transfers pachhattar minutes mein total ek lakh panchanve hazaar ka volume dikhate hain. Yeh unique funds ya money laundering ka proof nahi. Graph context aur exact source evidence ke saath system review lead banata hai.'),'backend/lead_engine.py Policy and run_engine; DEMO-RUNBOOK.md; tests/test_golden_flow.py. All numbers synthetic.');
const ch=s.charts.add('bar',{position:{left:64,top:195,width:650,height:380},categories:['7 din ka median','Event day*'],series:[{name:'Outgoing calls',values:[2,11],fill:c.cyan}],barOptions:{direction:'column',grouping:'clustered',gapWidth:120},hasLegend:false,chartFill:c.bg,plotAreaFill:c.bg,xAxis:{textStyle:{typeface:family,fontSize:23,fill:c.muted},line:{fill:'#476071',width:1}},yAxis:{min:0,max:12,majorUnit:3,textStyle:{typeface:family,fontSize:20,fill:c.muted},majorGridlines:{fill:'#243847',width:1}},dataLabels:{showValue:true,position:'outEnd',textStyle:{typeface:family,fontSize:28,fill:c.ink,bold:true}}});applyPresentationChartFont(ch,{fontFamily:family});
txt(s,'3 transfers',785,190,410,65,42,c.cyan,true);txt(s,'75 minutes mein\nINR 1,95,000 transfer volume',785,260,410,100,28,c.muted);txt(s,'Threshold visible hai',785,417,410,50,30,c.ink,true);txt(s,'max(5, 3 × 2) = 6 calls\n11 observed calls > 6',785,475,410,85,26,c.muted);txt(s,'Synthetic example. *Event day replay time tak. Transfer volume mein wahi funds dobara count ho sakte hain.',64,629,1100,49,18,c.amber);
s=base('Technical approach',5,note(5,'Frontend React, TypeScript aur Cytoscape par hai. FastAPI typed requests serve karta hai. Structured identifiers deterministic parsers se aate hain. spaCy NER optional local model ke available hone par use hota hai, fallback bhi hai. NetworkX bounded shortest paths compute karta hai. Temporal rules main lead engine hain. Isolation Forest secondary anomaly triage hai. Local SQLite investigator decisions rakhta hai. Hum LLM, GNN ya universal Hindi OCR implemented hone ka claim nahi karte.'),'frontend/package.json; backend/intake_parser.py; backend/ner_service.py; backend/demo_paths.py; backend/lead_engine.py; backend/behavioral_profiler.py; api/index.py.');
const rows=[['Input aur extraction','Controlled CSV/TXT, regex, optional spaCy NER'],['Graph aur identity','NetworkX paths, evidence links, reversible review'],['Signals aur review','Temporal rules, secondary Isolation Forest triage'],['Interface aur storage','React + Cytoscape, FastAPI, local SQLite']];
rows.forEach((r,i)=>{txt(s,r[0],64,191+i*108,380,50,29,c.cyan,true);txt(s,r[1],470,191+i*108,738,74,28,c.muted)});txt(s,'Core demo ko external AI API ki zaroorat nahi hai.',64,638,1100,30,22,c.ink);
s=base('Live demo: ek case, ek evidence chain',6,note(6,'Ab live demo kholte hain. Pehle source files dikhayenge. R.K. Sharma match ko exact phone aur vehicle evidence se review karenge. Phir Rahul se Vikram ka path compute karke Lead 17 kholenge. Transfer signal se E-TX-01 ka exact source row dikhayenge. Last mein Needs more evidence review aur audit trail dikhayenge. Har screen par sirf ek proof point. Demo ka separate target do minute tees second hai; yeh rehearsal target hai, measured claim nahi.'),'DEMO-RUNBOOK.md; frontend/src/components/NetworkWorkspace.tsx; local route /#/app.');
[['00:00–00:20','Case aur source records'],['00:20–00:50','Identity match ka human review'],['00:50–01:15','Rahul–Vikram path'],['01:15–02:00','Lead 17 aur exact evidence'],['02:00–02:30','Review decision aur audit trail']].forEach((r,i)=>{txt(s,r[0],64,187+i*83,255,45,27,c.cyan,true);txt(s,r[1],345,187+i*83,820,53,30,c.ink)});txt(s,'Demo target: 2:30. Local workspace primary, captured run backup.',64,630,1090,35,21,c.muted);
s=base('Prototype proof aur current boundaries',7,note(7,'Aaj tests folder ke targeted backend suite mein ek sau ek tests pass hue, do dependency warnings ke saath. Yeh correctness checks hain, real-world accuracy nahi. Public demo deploy hai aur core workspace bina sign-in khulta hai. Local review SQLite mein persist hota hai, lekin current Vercel temporary storage durable nahi hai. Official PS mein influential entities ki requirement confirm hui toh dedicated ranking abhi gap hai. Agency validation, multi-user security aur scale benchmark future work hain.'),'Fresh command: .venv/Scripts/python.exe -m pytest tests -q => 101 passed, 2 warnings, 22.99s. Repository inspection 2026-09-06. api/index.py uses /tmp/veil-state.');
txt(s,'101',64,185,530,120,92,c.cyan,true);txt(s,'Backend tests passed',64,315,530,50,30,c.ink,true);txt(s,'Synthetic inputs par implementation checks\nReal-world accuracy abhi measure nahi hui',64,388,530,110,27,c.muted);txt(s,'Public prototype available',64,558,530,50,26,c.ink,true);
txt(s,'Production se pehle',700,190,500,60,34,c.amber,true);txt(s,'Durable hosted storage\nAuthenticated reviewers\nCase-level access controls\nRepresentative evaluation\nInfluential-node ranking validation',700,280,505,292,29,c.muted);txt(s,'Test run: 6 Sep 2026. 2 dependency warnings.',64,638,1050,30,18,c.muted);
s=base('Selection ke baad agla milestone',8,note(8,'Selection ke baad hamara next milestone supervised pilot readiness hai. Pehle controlled evaluation set par false merges, missed entities aur source traceability measure karenge. Hosted state ko durable storage mein shift karenge. Domain mentor ke saath task timing aur usability validate karenge. Agar official PS require karta hai toh explainable centrality ranking ko benchmark karenge. Aaj hum working vertical slice, evidence traceability aur clear hardening plan dikha rahe hain. Hamara request internal selection aur domain mentorship hai.'),'Proposed roadmap, not completed work. SIH-SCOPE-FREEZE.md; verified implementation gaps.');
txt(s,'Agla measurable proof',64,210,1100,60,39,c.cyan,true);txt(s,'Fresh evaluation cases par entity quality,\nfalse merges aur evidence coverage measure karna',64,293,1100,105,35,c.ink);txt(s,'Pilot ki foundation',64,463,520,48,29,c.cyan,true);txt(s,'Durable data aur reviewer access',64,522,1050,55,29,c.muted);txt(s,'Internal selection + domain mentorship',64,617,1100,45,30,c.ink,true);
s=base('Backup: source ka exact record',9,note(9,'Agar judge provenance pooche toh yeh backup dikhana hai. Yeh pehle captured synthetic run hai. E-TX-01 ka filename, row, timestamp aur raw excerpt inspect hota hai. Source traceability aur source ki factual correctness alag cheezein hain. Hum unverified source ko verified fact nahi bana rahe.'),'artifacts/first-round/screenshots/05-evidence-provenance.png; backend/demo_repository.py.');await shot(s,'05-evidence-provenance.png',64,168,1152,485);txt(s,'Pehle captured synthetic run. Exact source locator aur verification state.',64,663,1060,27,18,c.muted);
s=base('Backup: influence requirement ka status',10,note(10,'Public mirror mein key individuals identify karne ka requirement mila, official version confirm karna baaki hai. Active backend mein dedicated centrality ranking verify nahi hui. Existing path aur clustering coefficient influential-person detector nahi hain. Agle iteration mein degree aur betweenness ko explainable ranking ke roop mein evaluate kar sakte hain. Ranking source coverage se affected hogi aur leadership ya guilt ka label nahi hogi.'),'README-PREVIOUS.md; backend/demo_paths.py; backend/behavioral_profiler.py; repository search for degree, centrality, pagerank, betweenness. PS mirror: https://sihone.pages.dev/ps/26189; official confirmation pending.');
txt(s,'Verified abhi',64,205,520,60,36,c.cyan,true);txt(s,'Bounded graph paths\nSource-linked relationships\nLocal clustering feature',64,300,540,180,31,c.muted);txt(s,'Next iteration',700,205,520,60,36,c.amber,true);txt(s,'Explainable centrality ranking\nCoverage aur stability checks\nAnalyst validation',700,300,520,180,31,c.muted);txt(s,'Central node ka meaning context se aayega. Leadership ka automatic conclusion nahi.',64,598,1130,62,25,c.ink);
s=base('Backup: evaluation plan',11,note(11,'Evaluation mein positive planted case ke saath benign controls bhi honge. Same naam aur alag phone ko false merge nahi karna chahiye. Missing source par signal suppress ya clearly flag hona chahiye. Edge remove karne par computed path badalna chahiye. Held-out records par precision recall report karenge. Task timing manual baseline aur tool-assisted flow ke saath same task par compare karenge. Targets ko achieved results nahi bolenge.'),'tests/test_resolution.py; tests/test_golden_flow.py; backend/lead_engine.py. Proposed additional evaluation, not measured outcome.');
[['False merges','Same naam, alag identifiers par identity alag rahe'],['Evidence coverage','Har surfaced relationship ka locator resolve ho'],['Negative controls','Benign burst ko crime label na mile'],['Workflow timing','Same task ka manual aur assisted time compare ho']].forEach((r,i)=>{txt(s,r[0],64,194+i*106,345,55,29,c.cyan,true);txt(s,r[1],445,194+i*106,760,78,28,c.muted)});txt(s,'Planned evaluation. Accuracy aur time-saving percentage abhi claim nahi karte.',64,636,1090,35,20,c.amber);
s=base('Backup: technical Q&A',12,note(12,'Hardcoded? Demo inputs fixed hain, lekin engine rules aur graph se result calculate karta hai. AI kahan? Optional spaCy extraction aur secondary Isolation Forest; main temporal lead deterministic hai. Deploy ready? Public prototype live hai, production storage aur security incomplete hain. Impact? Reduced cross-referencing expected benefit hai; measured saving abhi nahi. Agar answer unknown ho, verification step batao aur number invent mat karo.'),'backend/lead_engine.py; backend/ner_service.py; backend/behavioral_profiler.py; api/index.py.');
[['Lead hardcoded hai?','Inputs synthetic hain. Result backend calculate karta hai.'],['AI kahan use hua?','Optional NER aur secondary anomaly triage mein.'],['Production-ready hai?','Public demo live hai. Hardening abhi pending hai.'],['Impact kitna hai?','Time-saving hypothesis ko pilot mein measure karenge.']].forEach((r,i)=>{txt(s,r[0],64,194+i*106,400,58,29,c.cyan,true);txt(s,r[1],505,194+i*106,700,80,28,c.muted)});
await fs.writeFile(W+'/.build/notes.json',JSON.stringify(notes,null,2));
const candidate=W+'/.build/candidate.pptx';await(await PresentationFile.exportPptx(p)).save(candidate);
await fs.mkdir(W+'/.build/render',{recursive:true});
for(let i=0;i<p.slides.items.length;i++){const slide=p.slides.items[i];const png=await p.export({slide,format:'png',scale:1});await fs.writeFile(W+'/.build/render/slide-'+String(i+1).padStart(2,'0')+'.png',new Uint8Array(await png.arrayBuffer()));console.log('Rendered',i+1);}
const result=await finalizePresentation({workspaceDir:W,candidatePath:candidate,finalPath:W+'/output/Network-Intel-Internal-Hackathon-Hinglish.pptx',pythonExecutable:'C:/Users/tanis/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',integrityValidatorPath:SK+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:SK+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit'],fontPolicy:{basis:'design',families:[family]},materializeLiteralChartWorkbooks:true,requiredNativeChartOwnerSlides:[4],requiredNativeTableOwnerSlides:[],verifyArtifactToolImport:true,receiptPath:W+'/.build/validation.json'});
console.log(JSON.stringify(result));



