import {useEffect,useRef} from 'react';
import cytoscape from 'cytoscape';
import type {Entity,Edge} from './types';
export const colors:Record<string,string>={Person:'#79b7df',Phone:'#70c4b2',Account:'#c2a0e1',Vehicle:'#d9b777',Location:'#d78d91',Organization:'#97a8ae',Alias:'#a8b4c2'};
export default function Graph({entities,edges,path,focus,onSelect,fit}:{entities:Entity[];edges:Edge[];path:string[];focus:string;onSelect:(id:string,edge:boolean)=>void;fit:number}){
 const container=useRef<HTMLDivElement>(null), cy=useRef<cytoscape.Core|null>(null), select=useRef(onSelect); select.current=onSelect;
 useEffect(()=>{if(!container.current)return;const instance=cytoscape({container:container.current,elements:[...entities.map(n=>({data:{...n,color:colors[n.type]},position:{x:n.x,y:n.y*.50}})),...edges.map(e=>({data:{...e,label:e.type}}))],layout:{name:'preset',padding:45},minZoom:.35,maxZoom:2,style:[{selector:'node',style:{label:'data(label)','background-color':'#18272d','border-color':'data(color)','border-width':2,color:'#dce6e9','font-size':16,'text-valign':'bottom','text-margin-y':12,width:42,height:42,'text-background-color':'#111a1e','text-background-opacity':.9,'text-background-padding':'4px'}},{selector:'node[type="Account"]',style:{shape:'round-rectangle'}},{selector:'node[type="Phone"]',style:{shape:'round-rectangle',width:27,height:43}},{selector:'node[type="Location"]',style:{shape:'diamond'}},{selector:'node[type="Vehicle"]',style:{shape:'round-rectangle',width:50,height:30}},{selector:'node[type="Organization"]',style:{shape:'hexagon'}},{selector:'edge',style:{label:'data(label)',width:1.4,'line-color':'#415258','target-arrow-color':'#415258','target-arrow-shape':'triangle','curve-style':'bezier',color:'#a3b3ba','font-size':12,'text-rotation':'autorotate','text-background-color':'#111a1e','text-background-opacity':1,'text-background-padding':'3px'}},{selector:'edge[status="inferred"]',style:{'line-style':'dashed','line-color':'#c8a76b'}},{selector:'.highlight',style:{'border-color':'#aff3d0','border-width':4,'line-color':'#91d8b5','target-arrow-color':'#91d8b5',width:3}},{selector:'node.highlight',style:{width:46,height:46}}]});cy.current=instance;instance.on('tap','node',e=>select.current(e.target.id(),false));instance.on('tap','edge',e=>select.current(e.target.id(),true));const observer=new ResizeObserver(()=>{instance.resize();instance.fit(undefined,45)});observer.observe(container.current);return()=>{observer.disconnect();instance.destroy()}},[entities,edges]);
 useEffect(()=>{const instance=cy.current;if(!instance)return;instance.elements().removeClass('highlight');[...path,focus].filter(Boolean).forEach(id=>instance.getElementById(id).addClass('highlight'))},[path,focus,edges]);
 useEffect(()=>{cy.current?.fit(undefined,45)},[fit]);
 return <div ref={container} className="graph" aria-label="Interactive entity graph. Select an entity or relationship; equivalent controls are in the entity selector and evidence drawer."/>;
}
