import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';

const artifacts=path.resolve('../artifacts/redesign');
test('judge flow: sources → resolution → path → signals → evidence → review → audit',async({page},testInfo)=>{
 await mkdir(artifacts,{recursive:true});
 const errors:string[]=[],failed:string[]=[],external:string[]=[],requests:string[]=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 page.on('requestfailed',r=>failed.push(r.url()+': '+r.failure()?.errorText));
 page.on('response',r=>{if(r.status()>=400)failed.push(r.url()+': '+r.status())});
 await page.route('**/*',route=>{const url=route.request().url();if(!url.startsWith('http://127.0.0.1:8001')&&!url.startsWith('data:')){external.push(url);return route.abort()}return route.continue()});
 page.on('request',r=>{if(r.url().includes('/api/'))requests.push(new URL(r.url()).pathname)});
 const started=Date.now();
 await page.goto('/#/app');await expect(page.getByRole('heading',{name:/^Operation Trinetra/})).toBeVisible();
 await expect(page.getByRole('banner').getByText('Synthetic Demonstration Data',{exact:true})).toBeVisible();
 for(const route of ['/api/cases/demo','/api/cases/demo/graph','/api/cases/demo/leads','/api/cases/demo/sources'])expect(requests.filter(r=>r===route)).toHaveLength(1);
 await page.getByRole('button',{name:'Data Sources',exact:true}).click();
 await expect(page.locator('.source-grid>article')).toHaveCount(4);
 for(const filename of ['report.txt','cdr.csv','transactions.csv','vehicles.csv'])await expect(page.locator('.source-grid').getByText(filename,{exact:true})).toBeInViewport();
 await page.screenshot({path:path.join(artifacts,'01-processed-sources.png')});
 await page.getByRole('button',{name:'Continue to resolution review',exact:true}).click();
 const resolution=page.getByRole('complementary',{name:'Entity resolution review'});
 await expect(resolution.getByText('Exact shared phone',{exact:true})).toBeVisible();
 await expect(resolution.getByText('Exact shared vehicle',{exact:true})).toBeVisible();
 await page.getByLabel('Decision reason',{exact:true}).fill('P101 and the shared vehicle have matching source references. Confirm for synthetic demonstration.');
 await page.screenshot({path:path.join(artifacts,'02-resolution-review.png')});
 await page.getByRole('button',{name:'Confirm Match',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Match confirmed');
 await page.getByRole('button',{name:'Network',exact:true}).click();
 await page.getByRole('textbox',{name:'Search entities',exact:true}).fill('Rahul');
 await expect(page.getByRole('listbox')).toBeVisible();
 await page.getByRole('textbox',{name:'Search entities',exact:true}).press('Enter');
 await expect(page.getByRole('complementary',{name:'Investigation inspector'})).toContainText('Confirmed aliases');
 await expect(page.getByRole('complementary',{name:'Investigation inspector'})).toContainText('EVIDENCE DENSITY');
 await expect(page.getByRole('complementary',{name:'Investigation inspector'})).not.toContainText('RISK INDEX');
 await page.getByRole('combobox',{name:'Path start',exact:true}).selectOption('rahul');
 await page.getByRole('combobox',{name:'Path end',exact:true}).selectOption('vikram');
 const pathResponse=page.waitForResponse(r=>r.url().includes('/api/cases/demo/path?')&&r.status()===200);
 await page.getByRole('button',{name:'Find Path',exact:true}).click();
 const computed=await (await pathResponse).json();expect(computed.path_length).toBe(6);expect(computed.steps.every((s:{evidence_ids:string[]})=>s.evidence_ids.length>0)).toBeTruthy();
 await expect(page.getByTestId('entity-graph')).toHaveAttribute('data-path-count','13');
 await expect(page.getByRole('heading',{name:'6 hops. Every link inspectable.'})).toBeVisible();
 await page.screenshot({path:path.join(artifacts,'03-network-path.png')});
 const bounds=await page.getByTestId('entity-graph').boundingBox();
 await page.getByRole('button',{name:/LEAD INBOX/}).click();
 await page.getByRole('button',{name:'Open Lead 17',exact:true}).click();
 await expect(page.getByRole('heading',{name:'What happened?',exact:true})).toBeVisible();
 const leadBounds=await page.getByTestId('entity-graph').boundingBox();
 expect(leadBounds).not.toBeNull();expect(leadBounds?.x).toBe(bounds?.x);expect(leadBounds?.width).toBe(bounds?.width);
 const burst=page.locator('.computed-signal').filter({has:page.locator('summary').filter({hasText:'2 calls/day'})});
 const transfer=page.locator('.computed-signal').filter({has:page.locator('summary').filter({hasText:'3 connected transfers'})});
 await burst.locator('summary').first().click();await expect(burst).toContainText('median');
 await page.screenshot({path:path.join(artifacts,'04-lead-explanation.png')});
 await transfer.locator('summary').first().click();await expect(transfer).toContainText('75000');
 await transfer.getByRole('button',{name:'Open evidence E-TX-01',exact:true}).click();
 await expect(page.getByRole('heading',{name:'transactions-2026-08-15.csv',exact:true})).toBeVisible();
 await expect(page.getByText('Row 2',{exact:true})).toBeVisible();
 await page.screenshot({path:path.join(artifacts,'05-evidence-provenance.png')});
 await page.getByRole('button',{name:'Back to investigation',exact:true}).click();
 await page.locator('.review-disclosure>summary').click();
 await page.getByRole('textbox',{name:"Reviewer's name",exact:true}).fill('SIH demo investigator');
 await page.getByRole('combobox',{name:'Lead review action',exact:true}).selectOption('NEEDS_MORE_EVIDENCE');
 await page.getByRole('textbox',{name:'Review reasoning',exact:true}).fill('Verify original CDR rows and transaction purpose before further inquiry.');
 await page.getByRole('button',{name:'Review submission',exact:true}).click();
 await page.getByRole('button',{name:'Confirm submission',exact:true}).click();
 await expect(page.locator('.review-success')).toContainText('Saved: Needs more evidence');
 await page.getByRole('button',{name:'Audit Trail',exact:true}).click();
 await page.getByRole('combobox',{name:'Activity event type',exact:true}).selectOption('LEAD_REVIEW_SUBMITTED');
 await page.getByRole('button',{name:'Apply filters',exact:true}).click();
 await expect(page.locator('.activity-card')).toHaveCount(1);
 await expect(page.locator('.activity-card')).toContainText('UNREVIEWED → NEEDS_MORE_EVIDENCE');
 await page.screenshot({path:path.join(artifacts,'06-audit-history.png')});
 const duration=(Date.now()-started)/1000;
 expect(duration).toBeLessThan(180);expect(errors).toEqual([]);expect(failed).toEqual([]);expect(external).toEqual([]);
 const report={duration_seconds:duration,viewport:page.viewportSize(),console_errors:errors,failed_requests:failed,external_requests:external,api_requests:requests,computed_path:computed.path_length};
 await writeFile(path.join(artifacts,'golden-flow-verification.json'),JSON.stringify(report,null,2));
 await testInfo.attach('golden-flow-verification',{body:JSON.stringify(report,null,2),contentType:'application/json'});
 await page.reload();await page.getByRole('button',{name:/LEAD INBOX/}).click();await page.getByRole('button',{name:'Open Lead 17',exact:true}).click();
 await expect(page.locator('.drawer-body')).toContainText('NEEDS_MORE_EVIDENCE');
});

test('failure recovery, graph controls, keyboard focus, empty states and laptop layouts',async({page})=>{
 await page.route('**/api/cases/demo',r=>r.fulfill({status:503,body:'Service unavailable'}));
 await page.goto('/#/app');await expect(page.getByRole('alert')).toContainText('unavailable');
 await page.unroute('**/api/cases/demo');await page.getByRole('button',{name:'Retry connection'}).click();
 await expect(page.getByRole('heading',{name:'Operation Trinetra'})).toBeVisible();
 await page.getByRole('textbox',{name:'Search entities'}).fill('no-such-entity');await expect(page.getByText('No matching entity. Try Rahul, P101 or A17.')).toBeVisible();
 await page.getByRole('textbox',{name:'Search entities'}).press('Escape');
 await page.getByRole('button',{name:'Zoom in',exact:true}).click();const zoom=await page.getByLabel('Graph zoom').textContent();
 await page.getByRole('button',{name:'Zoom out',exact:true}).click();expect(await page.getByLabel('Graph zoom').textContent()).not.toBe(zoom);
 await page.getByRole('button',{name:'Reset graph view',exact:true}).click();await page.getByRole('button',{name:'Fit graph',exact:true}).click();
 await page.route('**/api/cases/demo/path?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Backend temporarily unavailable. Retry Find path.'}})}));
 await page.getByRole('button',{name:'Find Path',exact:true}).click();await expect(page.getByRole('alert')).toContainText('temporarily unavailable');
 await expect(page.getByTestId('entity-graph')).toBeVisible();await page.unroute('**/api/cases/demo/path?*');
 await page.getByRole('button',{name:'Find Path',exact:true}).click();await expect(page.getByRole('heading',{name:'6 hops. Every link inspectable.'})).toBeVisible();
 await page.getByRole('button',{name:/LEAD INBOX/}).click();await page.getByRole('combobox',{name:'Review priority filter',exact:true}).selectOption('LOW');await expect(page.getByText('No computed leads match this priority.',{exact:false})).toBeVisible();
 await page.getByRole('textbox',{name:'Search entities'}).focus();await page.keyboard.press('Tab');
 expect(await page.evaluate(()=>getComputedStyle(document.activeElement!).outlineStyle)).not.toBe('none');
 for(const size of [{width:1280,height:720},{width:1440,height:900}]){
  await page.setViewportSize(size);await expect(page.getByTestId('entity-graph')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight)).toBeTruthy();
 }
 await page.getByRole('button',{name:'Timeline',exact:true}).click();await page.getByRole('combobox',{name:'Activity event type',exact:true}).selectOption('transfer');
 await page.getByRole('combobox',{name:'Timeline entity',exact:true}).selectOption('A17');
 await page.getByRole('button',{name:'Open evidence E-TX-01',exact:true}).click();await expect(page.getByText('Row 2',{exact:true})).toBeVisible();
});
