import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
const folder=path.resolve('../artifacts/redesign');
test('redesigned pages, contextual navigation, filters, responsive drawers and evidence continuity',async({page})=>{
 await mkdir(folder,{recursive:true});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.goto('/#/app');const nav=page.getByRole('navigation',{name:'Investigation pages'});
 await expect(page.getByTestId('entity-graph')).toBeVisible();
 await page.screenshot({path:path.join(folder,'07-network-default.png')});
 await nav.getByRole('button',{name:'Case Overview',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Investigation inputs'})).toBeVisible();await expect(page.locator('.overview-source')).toHaveCount(4);
 await page.screenshot({path:path.join(folder,'08-case-overview.png')});
 await page.getByRole('button',{name:'Continue Entity Review',exact:true}).click();
 await page.getByLabel('Resolution proposal',{exact:true}).selectOption('MP-amit-a-verma');
 await expect(page.locator('.identity-comparison')).toContainText('A. Verma');
 const proposal=await page.getByLabel('Resolution proposal',{exact:true}).inputValue();
 await page.locator('.identity-card').first().getByRole('button',{name:/Open evidence/}).first().click();
 await expect(page.getByRole('complementary',{name:'Investigation inspector'})).toContainText('Exact locator');
 await expect(page.getByLabel('Resolution proposal',{exact:true})).toHaveValue(proposal);
 await page.getByRole('button',{name:'Back to investigation',exact:true}).click();
 await expect(page.getByLabel('Resolution proposal',{exact:true})).toHaveValue(proposal);
 await nav.getByRole('button',{name:'Timeline',exact:true}).click();
 await expect(page.getByRole('complementary',{name:'Entity resolution review'})).toHaveCount(0);
 await expect(nav.locator('[aria-current="page"]')).toHaveCount(1);
 await page.getByLabel('Activity event type',{exact:true}).selectOption('transfer');await page.getByLabel('Timeline entity',{exact:true}).selectOption('A17');
 await expect(page.locator('.activity-card').first()).toContainText('Transfer');
 await page.screenshot({path:path.join(folder,'09-timeline.png')});
 await page.getByRole('button',{name:'Open in Network',exact:true}).first().click();await expect(page.getByTestId('entity-graph')).toBeVisible();
 await page.getByRole('textbox',{name:'Search entities',exact:true}).fill('Rahul');await page.getByRole('textbox',{name:'Search entities',exact:true}).press('Enter');
 await page.getByRole('button',{name:'Focus path',exact:true}).click();
 await page.getByRole('button',{name:'Find Connection From Here',exact:true}).click();await expect(page.getByLabel('Path start',{exact:true})).toHaveValue('rahul');
 await page.getByRole('button',{name:/^Filters/}).click();
 await page.getByLabel('Graph entity type',{exact:true}).selectOption('Phone');
 await expect(page.locator('.canvas-note')).toContainText('2 of');
 await page.getByLabel('Graph entity type',{exact:true}).selectOption('');
 await page.getByLabel('Graph relationship type',{exact:true}).selectOption('CALLED');await expect(page.locator('.canvas-note')).toContainText('1 relationships');
 await page.getByLabel('Graph from',{exact:true}).fill('2030-01-01T00:00');await expect(page.locator('.canvas-note')).toContainText('0 relationships');
 await page.getByRole('button',{name:'Find Path',exact:true}).click();await expect(page.getByRole('heading',{name:'6 hops. Every link inspectable.'})).toBeVisible();await expect(page.getByLabel('Graph from',{exact:true})).toHaveValue('');
 await page.getByRole('button',{name:/^Filters/}).click();
 await page.getByRole('button',{name:'Legend',exact:true}).click();await expect(page.locator('.legend')).toHaveCount(1);await page.getByRole('button',{name:'Legend',exact:true}).click();await expect(page.locator('.legend')).toHaveCount(0);
 await nav.getByRole('button',{name:'Lead Inbox',exact:true}).click();await page.getByLabel('Inbox priority').selectOption('LOW');await expect(page.getByText('No leads match these filters')).toBeVisible();await page.getByRole('button',{name:'Clear filters',exact:true}).click();
 await page.getByLabel('Inbox category').selectOption('FINANCIAL');await expect(page.locator('.queue-row')).toHaveCount(1);const currentReviewStatus=await page.getByLabel('Inbox review status').locator('option').nth(1).getAttribute('value');expect(currentReviewStatus).toBeTruthy();await page.getByLabel('Inbox review status').selectOption(currentReviewStatus!);await expect(page.locator('.queue-row')).toHaveCount(1);
 await page.getByRole('button',{name:'Inspect Lead 17',exact:true}).click();await expect(page.locator('.drawer-body')).toContainText('What happened?');
 await page.getByLabel('Inbox from').fill('2030-01-01T00:00');await expect(page.locator('.queue-row')).toHaveCount(0);await page.getByRole('button',{name:'Clear filters',exact:true}).click();
 await page.screenshot({path:path.join(folder,'10-lead-inbox.png')});
 await page.getByRole('button',{name:'Investigate in Network',exact:true}).click();await expect(page.getByTestId('entity-graph')).toHaveAttribute('data-path-count','13');await expect(page.locator('.canvas-note')).toContainText('Event window active');
 await page.getByRole('button',{name:'View Timeline',exact:true}).click();await expect(page.getByLabel('Activity from')).not.toHaveValue('');
 await nav.getByRole('button',{name:'Network',exact:true}).click();
 for(const viewport of [{width:1366,height:768},{width:1440,height:900},{width:1920,height:1080},{width:768,height:1024}]){
  await page.setViewportSize(viewport);await expect(page.getByRole('banner').getByText('Synthetic Demonstration Data',{exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight)).toBeTruthy();
  await expect(page.getByTestId('entity-graph')).toBeVisible();
  await page.screenshot({path:path.join(folder,`responsive-${viewport.width}.png`)});
 }
 const inspectorToggle=page.getByRole('button',{name:/inspector$/});if(await inspectorToggle.getAttribute('aria-label')==='Expand inspector')await inspectorToggle.click();await expect(page.getByRole('complementary',{name:'Investigation inspector'})).toBeVisible();await page.getByRole('button',{name:'Collapse inspector',exact:true}).click();await expect(page.getByRole('complementary',{name:'Investigation inspector'})).toHaveCount(0);
 await page.setViewportSize({width:1366,height:768});await page.getByRole('button',{name:'Collapse navigation',exact:true}).click();await expect(page.locator('.sidebar-collapsed')).toBeVisible();await page.getByRole('button',{name:'Expand navigation',exact:true}).click();
 await page.emulateMedia({reducedMotion:'reduce'});expect(await page.getByRole('button',{name:'Fit graph'}).evaluate(el=>getComputedStyle(el).transitionDuration)).toBe('0s');
 expect(errors).toEqual([]);await writeFile(path.join(folder,'redesign-verification.json'),JSON.stringify({console_errors:errors,viewports:[1366,1440,1920,768],contextual_navigation:true,graph_filters:true,lead_filters:true,reduced_motion:true},null,2));
});

test('preserved report extraction and behavioral tabs keep evidence and graph actions connected',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.goto('/#/app');await page.getByRole('navigation').getByRole('button',{name:'Data Sources',exact:true}).click();
 await page.getByRole('button',{name:'Report extraction',exact:true}).click();await expect(page.locator('.report-intelligence-view')).toBeVisible();
 await expect(page.locator('.entity-table tbody tr').first()).toBeVisible();
 await page.screenshot({path:path.join(folder,'11-report-extraction.png')});
 await page.locator('.entity-table .evidence-btn').first().click();await expect(page.getByRole('complementary',{name:'Investigation inspector'})).toContainText('Exact locator');
 await page.getByRole('button',{name:'Close inspector',exact:true}).click();
 await page.getByRole('button',{name:'Behavioral profiles',exact:true}).click();await expect(page.locator('.anomaly-view-root')).toBeVisible();
 await page.screenshot({path:path.join(folder,'12-behavioral-profiles.png')});
 expect(errors).toEqual([]);
});
